# Generated by Django 4.2.5 on 2023-11-22 11:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Visa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Название визы', max_length=255, null=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, default='Название визы', null=True, verbose_name='Описание')),
                ('status', models.IntegerField(choices=[(1, 'Действует'), (2, 'Удалена')], default=1, verbose_name='Статус')),
                ('country', models.CharField(blank=True, default='Европа, Азия, Америка', max_length=255, null=True, verbose_name='Страны')),
                ('price', models.IntegerField(blank=True, default=5000, null=True, verbose_name='Цена')),
                ('duration', models.IntegerField(blank=True, default=5, null=True, verbose_name='Срок действия')),
                ('image', models.ImageField(upload_to='visas', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Виза',
                'verbose_name_plural': 'Визы',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Зарегистрирован'), (2, 'Проверяется'), (3, 'Принято'), (4, 'Отказано'), (5, 'Удалено')], default=1, verbose_name='Статус')),
                ('date_created', models.DateField(blank=True, default=datetime.datetime(2023, 11, 22, 11, 47, 15, 752450, tzinfo=datetime.timezone.utc), null=True, verbose_name='Дата создания')),
                ('date_of_formation', models.DateField(blank=True, default=datetime.datetime(2023, 11, 22, 11, 47, 15, 752450, tzinfo=datetime.timezone.utc), null=True, verbose_name='Дата формирования')),
                ('date_complete', models.DateField(blank=True, null=True, verbose_name='Дата завершения')),
                ('visas', models.ManyToManyField(null=True, to='visas.visa', verbose_name='Визы')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
