# Generated by Django 4.2.5 on 2023-12-26 22:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='Название визы', max_length=255, null=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, default='Описание визы', null=True, verbose_name='Описание')),
                ('status', models.IntegerField(choices=[(1, 'Действует'), (2, 'Удалена')], default=1, verbose_name='Статус')),
                ('country', models.CharField(blank=True, default='Европа, Азия, Америка', max_length=255, null=True, verbose_name='Страны')),
                ('price', models.IntegerField(blank=True, default=5000, null=True, verbose_name='Цена')),
                ('duration', models.IntegerField(blank=True, default=5, null=True, verbose_name='Срок действия')),
                ('image', models.ImageField(upload_to='visas', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Виза',
                'verbose_name_plural': 'Визы',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.IntegerField(blank=True, null=True, verbose_name='Время выполнение заказа (в днях)')),
                ('status', models.IntegerField(choices=[(1, 'Зарегистрирован'), (2, 'Проверяется'), (3, 'Принято'), (4, 'Отказано'), (5, 'Удалено')], default=1, verbose_name='Статус')),
                ('date_created', models.DateField(blank=True, default=datetime.datetime(2023, 12, 26, 22, 25, 49, 688229, tzinfo=datetime.timezone.utc), null=True, verbose_name='Дата создания')),
                ('date_of_formation', models.DateField(blank=True, default=datetime.datetime(2023, 12, 26, 22, 25, 49, 688229, tzinfo=datetime.timezone.utc), null=True, verbose_name='Дата формирования')),
                ('date_complete', models.DateField(blank=True, null=True, verbose_name='Дата завершения')),
                ('visas', models.ManyToManyField(null=True, to='visas.visa', verbose_name='Визы')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('is_moderator', models.BooleanField(default=False)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
