# Generated by Django 4.2.4 on 2023-12-26 23:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visas', '0002_rename_accepted_order_delivery_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 12, 26, 23, 23, 40, 225577, tzinfo=datetime.timezone.utc), null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_of_formation',
            field=models.DateField(blank=True, default=datetime.datetime(2023, 12, 26, 23, 23, 40, 225577, tzinfo=datetime.timezone.utc), null=True, verbose_name='Дата формирования'),
        ),
    ]
