# Generated by Django 4.2.7 on 2024-01-01 15:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visas', '0003_alter_order_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 1, 1, 15, 44, 35, 48914, tzinfo=datetime.timezone.utc), null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_of_formation',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 1, 1, 15, 44, 35, 48914, tzinfo=datetime.timezone.utc), null=True, verbose_name='Дата формирования'),
        ),
    ]
