# Generated by Django 4.2.7 on 2024-01-01 20:11

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visas', '0004_alter_order_date_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='moderator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='moderator', to=settings.AUTH_USER_MODEL, verbose_name='Модератор'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 1, 1, 20, 11, 33, 705121, tzinfo=datetime.timezone.utc), null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_of_formation',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 1, 1, 20, 11, 33, 705121, tzinfo=datetime.timezone.utc), null=True, verbose_name='Дата формирования'),
        ),
    ]
