# Generated by Django 4.2.7 on 2024-01-01 20:53

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('visas', '0005_order_moderator_order_user_alter_order_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 1, 1, 20, 53, 44, 906193, tzinfo=datetime.timezone.utc), null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_of_formation',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 1, 1, 20, 53, 44, 906193, tzinfo=datetime.timezone.utc), null=True, verbose_name='Дата формирования'),
        ),
        migrations.CreateModel(
            name='OrderVisa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='visas.order')),
                ('option', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='visas.visa')),
            ],
            options={
                'managed': True,
            },
        ),
    ]
