# Generated by Django 4.2.7 on 2024-01-01 20:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visas', '0006_alter_order_date_created_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordervisa',
            old_name='application',
            new_name='order',
        ),
        migrations.RenameField(
            model_name='ordervisa',
            old_name='option',
            new_name='visa',
        ),
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 1, 1, 20, 58, 37, 288491, tzinfo=datetime.timezone.utc), null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_of_formation',
            field=models.DateField(blank=True, default=datetime.datetime(2024, 1, 1, 20, 58, 37, 289488, tzinfo=datetime.timezone.utc), null=True, verbose_name='Дата формирования'),
        ),
    ]
