# Generated by Django 4.2.7 on 2024-01-03 12:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visas', '0007_rename_application_ordervisa_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='date_created',
            field=models.DateField(blank=True, default=datetime.date.today, null=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='date_of_formation',
            field=models.DateField(blank=True, null=True, verbose_name='Дата формирования'),
        ),
        migrations.DeleteModel(
            name='OrderVisa',
        ),
    ]
