# Generated by Django 4.2.7 on 2024-01-20 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visas', '0009_alter_visa_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='violation',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Нарушения'),
        ),
    ]
