# Generated by Django 4.2.4 on 2023-10-19 11:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('date_creation', models.DateField(blank=True, null=True)),
                ('date_formation', models.DateField(blank=True, null=True)),
                ('date_completion', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'orders',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('login', models.CharField(blank=True, max_length=255, null=True)),
                ('name', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=255)),
                ('password', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Vises',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(blank=True, max_length=255, null=True)),
                ('country', models.CharField(blank=True, max_length=255, null=True)),
                ('type', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=0, max_digits=255, null=True)),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('specialist', models.CharField(blank=True, max_length=255, null=True)),
                ('specialist_url', models.CharField(max_length=255)),
                ('url', models.CharField(max_length=255)),
                ('picture', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'vises',
                'managed': True,
            },
        ),
        migrations.CreateModel(
            name='OrdersVises',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'orders_vises',
                'managed': True,
            },
        ),
        migrations.AddField(
            model_name='orders',
            name='id_moderator',
            field=models.ForeignKey(blank=True, db_column='id_moderator', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='bmstu_lab.users'),
        ),
        migrations.AddField(
            model_name='orders',
            name='id_user',
            field=models.ForeignKey(blank=True, db_column='id_user', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='orders_id_user_set', to='bmstu_lab.users'),
        ),
    ]
