# Generated by Django 4.2.4 on 2023-10-19 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_lab', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orders',
            options={},
        ),
        migrations.AlterModelOptions(
            name='ordersvises',
            options={},
        ),
        migrations.AlterModelOptions(
            name='vises',
            options={},
        ),
    ]
