# Generated by Django 4.2.4 on 2023-10-19 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bmstu_exhibitions', '0002_alter_orders_options_alter_ordersvises_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vises',
            name='status',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
